triggerAuth:
  name: aciblobstorage-auth
  namespace: aks-workshop-dev
  secretTargetRefs:
  - parameter: connection
    name: web-jobs-storage-secret
    key: AzureWebJobsStorage
scaledObject:
  name: aciblob-scaledobject
  namespace: aks-workshop-dev
  scaleTargetRef:
    name: aciblobapp-deploy    
    apiVersion: apps/v1
    kind: Deployment
  minReplicaCount: 1
  maxReplicaCount: 100
  triggers:
  - type: azure-blob
    blobContainerName: aciimageblob
    blobCount: '5'
    connectionFromEnv: connection 
    triggerAuth: aciblobstorage-auth  